[Interface]
# Key for Clawbot
# Bouncing = 3
# NetShield = 0
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = uGGQxqa9uyD+aS+COwxVCRSoxFHDNCEND4rmVx297VE=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# MX-FREE#15
PublicKey = uK67VRNOHFP8JwJRqGdZ8Ax9Pu0M7ZGnHJ+DNq4TFiM=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 84.20.27.51:51820

PersistentKeepalive = 25