"""Student–Proctor contract layer (PML) — versioned artifacts and pre-reveal boundary."""

from renaissance_v4.game_theory.student_proctor.contracts_v1 import (
    CONTRACT_VERSION_STUDENT_PROCTOR_V1,
    FIELD_RETRIEVED_STUDENT_EXPERIENCE_V1,
    FIELD_STUDENT_CONTEXT_ANNEX_V1,
    GRADED_UNIT_TYPE_V1,
    PRE_REVEAL_FORBIDDEN_KEYS_V1,
    SCHEMA_REVEAL_V1,
    SCHEMA_STUDENT_CONTEXT_ANNEX_V1,
    SCHEMA_STUDENT_LEARNING_RECORD_V1,
    SCHEMA_STUDENT_OUTPUT_V1,
    SCHEMA_STUDENT_RETRIEVAL_SLICE_V1,
    TRADING_CONTEXT_BUCKET_KEYS_V1,
    illegal_pre_reveal_bundle_example_v1,
    legal_example_reveal_v1,
    legal_example_student_context_annex_v1,
    legal_example_student_learning_record_v1,
    legal_example_student_output_v1,
    validate_pre_reveal_bundle_v1,
    validate_reveal_v1,
    validate_student_context_annex_v1,
    validate_student_learning_record_v1,
    validate_student_output_v1,
)
from renaissance_v4.game_theory.student_proctor.cross_run_retrieval_v1 import (
    build_student_decision_packet_v1_with_cross_run_retrieval,
    project_student_learning_record_to_retrieval_slice_v1,
)
from renaissance_v4.game_theory.student_proctor.reveal_layer_v1 import (
    build_comparison_v1,
    build_reveal_v1_from_outcome_and_student,
    outcome_record_to_referee_truth_v1,
)
from renaissance_v4.game_theory.student_proctor.shadow_student_v1 import (
    emit_shadow_stub_student_output_v1,
    shadow_stub_student_outputs_for_outcomes,
)
from renaissance_v4.game_theory.student_proctor.student_context_builder_v1 import (
    SCHEMA_STUDENT_DECISION_PACKET_V1,
    attach_student_context_annex_v1,
    build_student_decision_packet_v1,
    fetch_bars_causal_up_to,
    validate_student_decision_packet_v1,
)
from renaissance_v4.game_theory.student_proctor.student_learning_store_v1 import (
    append_student_learning_record_v1,
    build_student_learning_record_v1_from_reveal,
    default_student_learning_store_path_v1,
    get_student_learning_record_by_id,
    list_student_learning_records_by_graded_unit_id,
    list_student_learning_records_by_run_id,
    list_student_learning_records_by_signature_key,
    load_student_learning_records_v1,
)

__all__ = [
    "CONTRACT_VERSION_STUDENT_PROCTOR_V1",
    "GRADED_UNIT_TYPE_V1",
    "FIELD_RETRIEVED_STUDENT_EXPERIENCE_V1",
    "FIELD_STUDENT_CONTEXT_ANNEX_V1",
    "PRE_REVEAL_FORBIDDEN_KEYS_V1",
    "SCHEMA_REVEAL_V1",
    "SCHEMA_STUDENT_CONTEXT_ANNEX_V1",
    "SCHEMA_STUDENT_RETRIEVAL_SLICE_V1",
    "SCHEMA_STUDENT_LEARNING_RECORD_V1",
    "SCHEMA_STUDENT_OUTPUT_V1",
    "TRADING_CONTEXT_BUCKET_KEYS_V1",
    "illegal_pre_reveal_bundle_example_v1",
    "legal_example_reveal_v1",
    "legal_example_student_context_annex_v1",
    "legal_example_student_learning_record_v1",
    "legal_example_student_output_v1",
    "validate_pre_reveal_bundle_v1",
    "validate_student_context_annex_v1",
    "validate_reveal_v1",
    "validate_student_learning_record_v1",
    "validate_student_output_v1",
    "build_student_decision_packet_v1_with_cross_run_retrieval",
    "project_student_learning_record_to_retrieval_slice_v1",
    "build_comparison_v1",
    "build_reveal_v1_from_outcome_and_student",
    "outcome_record_to_referee_truth_v1",
    "emit_shadow_stub_student_output_v1",
    "shadow_stub_student_outputs_for_outcomes",
    "SCHEMA_STUDENT_DECISION_PACKET_V1",
    "attach_student_context_annex_v1",
    "build_student_decision_packet_v1",
    "fetch_bars_causal_up_to",
    "validate_student_decision_packet_v1",
    "append_student_learning_record_v1",
    "build_student_learning_record_v1_from_reveal",
    "default_student_learning_store_path_v1",
    "get_student_learning_record_by_id",
    "list_student_learning_records_by_graded_unit_id",
    "list_student_learning_records_by_run_id",
    "list_student_learning_records_by_signature_key",
    "load_student_learning_records_v1",
]
