"""
baseline_report.py

Purpose:
Write renaissance_v4/reports/baseline_v1.md from ledger summary and scorecards.

Version:
v1.0

Change History:
- v1.0 Baseline v1 acceptance (architect).
"""

from __future__ import annotations

from pathlib import Path

_RENAISSANCE_V4_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REPORT_PATH = _RENAISSANCE_V4_ROOT / "reports" / "baseline_v1.md"


def write_baseline_report(
    path: Path | None,
    *,
    dataset_bars: int,
    summary: dict,
    scorecards: dict[str, dict],
    cumulative_pnl: float,
    validation_checksum: str,
    sanity: dict[str, int | float | str],
) -> Path:
    """
    Overwrite baseline markdown with portfolio metrics and per-signal scorecards.
    """
    out = path or DEFAULT_REPORT_PATH
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# RenaissanceV4 — Baseline Report v1",
        "",
        "Generated by replay validation. **Phases 8–11 are not integrated** (promotion/decay/portfolio gates disabled).",
        "",
        "## Dataset",
        "",
        f"- **Bars in replay:** {dataset_bars}",
        "",
        "## Portfolio metrics",
        "",
        f"- **Total closed trades:** {summary.get('total_trades', 0)}",
        f"- **Wins / losses:** {summary.get('wins', 0)} / {summary.get('losses', 0)}",
        f"- **Win rate:** {summary.get('win_rate', 0.0):.6f}",
        f"- **Gross / net PnL:** {summary.get('gross_pnl', 0.0):.8f} / {summary.get('net_pnl', 0.0):.8f}",
        f"- **Average PnL / expectancy:** {summary.get('average_pnl', 0.0):.8f}",
        f"- **Max drawdown (equity curve):** {summary.get('max_drawdown', 0.0):.8f}",
        f"- **Avg MAE / MFE:** {summary.get('avg_mae', 0.0):.8f} / {summary.get('avg_mfe', 0.0):.8f}",
        f"- **Cumulative simulated PnL (execution manager):** {cumulative_pnl:.8f}",
        f"- **Validation checksum:** `{validation_checksum}`",
        "",
        "## Per-signal scorecards",
        "",
    ]

    if not scorecards:
        lines.append("*No outcomes attributed to contributing signals (empty scorecards).*")
        lines.append("")
    else:
        for name, card in sorted(scorecards.items()):
            lines.append(f"### {name}")
            lines.append("")
            lines.append(f"- lifecycle (advisory): **{card.get('lifecycle_state', 'n/a')}**")
            lines.append(f"- trades: {card.get('total_trades', 0)}, win_rate: {card.get('win_rate', 0.0):.6f}")
            lines.append(f"- expectancy: {card.get('expectancy', 0.0):.8f}, max_drawdown: {card.get('max_drawdown', 0.0):.8f}")
            lines.append("")

    lines.extend(
        [
            "## Sanity check (required)",
            "",
            f"- **Bars with fusion `no_trade`:** {sanity.get('fusion_no_trade_bars', 0)}",
            f"- **Bars with fused long/short:** {sanity.get('fusion_directional_bars', 0)}",
            f"- **Bars risk blocked (not allowed):** {sanity.get('risk_blocked_bars', 0)}",
            f"- **Simulated opens (entries):** {sanity.get('entries_attempted', 0)}",
            f"- **Closed trades (outcomes recorded):** {sanity.get('closes_recorded', 0)}",
            "",
            "### Interpretation",
            "",
            "- **Trades occurring?** See total closed trades and opens.",
            "- **Overtrading?** Compare opens to bars; high open/bar ratio implies frequent re-entry.",
            "- **Stuck in no_trade?** Compare fusion no_trade bars to directional bars.",
            "- **Signals vs regimes:** Per-signal scorecards use outcomes tagged with contributing signals at entry; regime at exit is stored on each outcome.",
            "- **Risk overly restrictive?** Compare risk_blocked_bars to directional fusion bars.",
            "",
        ]
    )

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[baseline_report] Wrote {out.resolve()}")
    return out
