"""Phase 5.7.4 / 5.7.5 first approved paper-loop runtime + durable outcome store (CANONICAL #031 / #032)."""

from modules.paper_loop.models import (
    PaperLoopExecutionIntentLinkV1,
    PaperLoopOutcomePersistenceLinkV1,
    PaperLoopSignalApprovalLinkV1,
)
from modules.paper_loop.chris_scoring import (
    ChrisPaperArtifactBundleV1,
    ChrisPaperDecisionRecordV1,
    ChrisPaperOutcomeRecordV1,
    ChrisPaperRcsReflectionLinkV1,
    ChrisScoreSurfacesV1,
    compute_chris_score_surfaces,
    ensure_chris_paper_artifact_schema,
    read_chris_paper_bundles,
    validate_chris_artifact_bundle,
    write_chris_paper_artifact_bundle,
)
from modules.execution_adapter.coinbase_sandbox import CoinbaseSandboxVenueScenario
from modules.paper_loop.orchestration import PaperLoopOrchestrationResult, run_first_approved_paper_loop
from modules.paper_loop.outcome_store_sqlite import (
    PaperLoopStoreWriteResult,
    connect_paper_loop_outcome_store,
    count_outcomes_for_participant,
    ensure_paper_loop_outcome_schema,
    persistence_link_canonical_json,
    persistence_link_payload_hash,
    read_paper_loop_outcome,
    replay_canonical_tuple_from_store,
    write_paper_loop_outcome,
)
from modules.paper_loop.validation import (
    LOOP_APPROVAL_004,
    LOOP_HASH_003,
    LOOP_LINK_001,
    LOOP_OBS_007,
    LOOP_PAPER_005,
    LOOP_PERSIST_006,
    LOOP_REPLAY_008,
    LOOP_SCOPE_002,
    LoopValidationResult,
    execution_intent_link_from_dict,
    outcome_persistence_link_from_dict,
    signal_approval_link_from_dict,
    validate_approval_validity,
    validate_context_and_market_snapshot,
    validate_lineage_chain,
    validate_loop_replay_stability,
    validate_outcome_for_durable_store,
    validate_outcome_persistence_link_integrity,
    validate_pre_paper_integration,
    validate_scope_continuity,
    persistence_link_to_wire_dict,
)

__all__ = [
    "CoinbaseSandboxVenueScenario",
    "ChrisPaperArtifactBundleV1",
    "ChrisPaperDecisionRecordV1",
    "ChrisPaperOutcomeRecordV1",
    "ChrisPaperRcsReflectionLinkV1",
    "ChrisScoreSurfacesV1",
    "LOOP_APPROVAL_004",
    "LOOP_HASH_003",
    "LOOP_LINK_001",
    "LOOP_OBS_007",
    "LOOP_PAPER_005",
    "LOOP_PERSIST_006",
    "LOOP_REPLAY_008",
    "LOOP_SCOPE_002",
    "LoopValidationResult",
    "PaperLoopExecutionIntentLinkV1",
    "PaperLoopOrchestrationResult",
    "PaperLoopOutcomePersistenceLinkV1",
    "PaperLoopSignalApprovalLinkV1",
    "PaperLoopStoreWriteResult",
    "connect_paper_loop_outcome_store",
    "count_outcomes_for_participant",
    "compute_chris_score_surfaces",
    "ensure_chris_paper_artifact_schema",
    "read_chris_paper_bundles",
    "ensure_paper_loop_outcome_schema",
    "persistence_link_canonical_json",
    "persistence_link_payload_hash",
    "persistence_link_to_wire_dict",
    "read_paper_loop_outcome",
    "replay_canonical_tuple_from_store",
    "write_paper_loop_outcome",
    "execution_intent_link_from_dict",
    "outcome_persistence_link_from_dict",
    "run_first_approved_paper_loop",
    "signal_approval_link_from_dict",
    "validate_approval_validity",
    "validate_context_and_market_snapshot",
    "validate_lineage_chain",
    "validate_loop_replay_stability",
    "validate_outcome_for_durable_store",
    "validate_outcome_persistence_link_integrity",
    "validate_pre_paper_integration",
    "validate_scope_continuity",
    "validate_chris_artifact_bundle",
    "write_chris_paper_artifact_bundle",
]
